export const SET_DANH_SACH_PHONG = "SET_DANH_SACH_PHONG";

export const SET_THONG_TIN_PHONG = "SET_THONG_TIN_PHONG";

// 2 BIẾN NÀY ĐEM XUỐNG FILE CONSTANT.JSX RỒI THÌ EM XÓA FILE NÀY LUÔN IK NHA
// NHỚ CHECK LẠI CÁC CHỖ EM IMPORT 2 BIẾN NÀY ĐỂ FIX ĐƯỜNG DẪN LẠI CHO ĐÚNG NHÉ
// NHÌN CHUNG, THƯ MỤC APP EM CHỈ ĐỂ 2 FILE LÀ PAGE.JSX VÀ LAYOUT.JSX (NẾU CẦN)
